### ISSUE TITLE
Support for SQLAlchemy 2.0

### ISSUE THREAD

**Issue by mariusdkm** [yehoshuadimarsky/bcpandas#137]
We are moving our project to SQLAlchemy 2.0 and this is one of the last libraries, that doesn't support it.
Are there any issues with 2.0? And would you support a PR upgrading SQLAlchemy to 2.0?
If so I would be happy to contribute and fix any issues if they exist.

**Comment by yehoshuadimarsky** [comment]
Hi, yes we would most definitely welcome a PR to support SQLAlchemy 2.0. Great to hear more and more people are using this!

**Comment by yxiao315** [comment]
Is there any progress or plan release date?  my project use both Sql Server and Oracle, oracledb require SQLAlchemy >=2.0, now I have to change it back to use Cx_oracle if I want to use bcpandas.

**Comment by yehoshuadimarsky** [comment]
When the linked PR is merged. @borchero are you able to take a look, just to double check?

**Comment by namur007** [comment]
Any update on this?
