### ISSUE TITLE
Error: incorrect host-column number found in BCP format-file

### ISSUE THREAD

**Issue by erfannariman** [yehoshuadimarsky/bcpandas#19]
Just tried to install / use bcpandas on a colleagues laptop (windows 10) and got this strange error, could not make anything of it:

```console
SQLState = S1000, NativeError = 0
Error = [Microsoft][ODBC Driver 17 for SQL Server]Incorrect host-column number found in BCP format-file
```

**Comment by yehoshuadimarsky** [comment]
It's a BCP error, can you please post a sample of the data you are trying to upload? And/or the code?

**Comment by erfannariman** [comment]
Not sure if I can share the data, since it sensitive, but will share the code.

**Comment by yehoshuadimarsky** [comment]
Hi, please share the code and any data you can, I will close this issue soon otherwise, thanks
