### ISSUE TITLE
Pass dtype in to_sql

### ISSUE THREAD

**Issue by matthiasschuurmans** [yehoshuadimarsky/bcpandas#25]
Hi, thanks a lot for this package, I just found it and figured I'd give it a try, and it's very nice! 

I do have a question: is it possible somehow to pass a dtype along to `to_sql()`? I have my own dtype dict which I can pass with pandas' `to_sql()`, but I can't find that option here. I went into the bcpandas `to_sql()` function, it seems easy to me to pass it, first to `to_sql()`, then to `_create_table()` and then to pandas' own `SQLTable()` constructor. Am I missing something?

**Comment by yehoshuadimarsky** [comment]
I guess we could theoretically do that, although I would be concerned that it might interfere with the data load via BCP. But I guess we can try it. Can I ask you to submit a pull request?

**Comment by matthiasschuurmans** [comment]
Hey @yehoshuadimarsky , thanks for the reply. See https://github.com/yehoshuadimarsky/bcpandas/pull/26 for what I had in mind.
