### ISSUE TITLE
Allow the user to specify a delimiter and quote character for perf

### ISSUE THREAD

**Issue by AaronCritchley** [yehoshuadimarsky/bcpandas#34]
Firstly, thank you for an excellent package - this has saved me lots of time and is a wonderful implementation.

A suggestion - I am inserting multiple GB's of numerical data, the data is formatted in a known way so I know what characters would be suitable as quote chars and delims. If I could specify the characters I'd save lots of time in execution.

For example, when benchmarking a ~150MB DataFrame with ~1.25M rows, total execution takes 106 seconds, with the primary time being spent like so (non-exhaustive, just the longest sections):
```
get_delimiter - 18.6s
get_quotechar - 17s
replace_bools_and_insert - 63s
```

This would be very similar to #22, a concern was mentioned about wanting to check if the users delimiter is in the data set, perhaps this could be dealt with by a "check_delim_is_present" option/flag/argument that when present avoids the safe path in the pursuit of performance.

If you're happy with this change, I would be happy to raise an MR with an implementation / tests, just let me know.

**Comment by yehoshuadimarsky** [comment]
Ok, sure go ahead and open a PR
