### ISSUE TITLE
latest version doesn't seem to be available to pip

### ISSUE THREAD

**Issue by seanmccay** [yehoshuadimarsky/bcpandas#36]
Hey there, I'm new to Python so bear with me. 

ISSUE: 
PyPi only shows me up to version 0.2.2 using pip to install bcpandas...

Is this because I'm on an unsupported version of Python? I'm using 3.9.6. What can I do to get the latest version from PyPi?

**Comment by yehoshuadimarsky** [comment]
Correct, BCPandas only currently supports Python 3.6-3.8, see #29

**Comment by yehoshuadimarsky** [comment]
Added support for Python 3.9+ here https://github.com/yehoshuadimarsky/bcpandas/pull/40, will release a new version shortly
