### ISSUE TITLE
bcppath error

### ISSUE THREAD

**Issue by rdillinger** [yehoshuadimarsky/bcpandas#43]
Hi - not sure if I'm having trouble setting up sqlcreds correctly, or if this is a different problem. The to_sql is failing on the line 
bcp_path = bcp_path with Error: FileNotFoundError: [WinError 2] The system cannot find the file specified.

I'm using Jupyter notebook - the section highlighted right before it skips to the runcmd to show the error output is:

[librarypath]\bcpandas\main.py in to_sql(df, table_name, creds, sql_type, schema, index, if_exists, batch_size, debug, bcp_path, dtype, process_dest_table, print_output, delimiter, quotechar)
    456             schema=schema,
    457             batch_size=batch_size,
--> 458             bcp_path=bcp_path,
    459         )

Any advice? Thank you.

**Comment by yehoshuadimarsky** [comment]
you will need to figure out which BCP path the Jupyter notebook is trying to use. Try running
```
!which -a bcp
```

**Comment by sujijayasekar** [comment]
I am getting the similar error when i use bcpandas like below 

File "E:\Program Files\Python39\lib\subprocess.py", line 951, in __init__
    self._execute_child(args, executable, preexec_fn, close_fds,
  File "E:\Program Files\Python39\lib\subprocess.py", line 1420, in _execute_child
    hp, ht, pid, tid = _winapi.CreateProcess(executable, args,
FileNotFoundError: [WinError 2] The system cannot find the file specified

here is my code
bcpandas.to_sql(afibl_dbfdf, 'AFIBL_ISL_DBF' , creds, if_exists='append',index=False  )

any idea?
