### ISSUE TITLE
Document API

### ISSUE THREAD

**Issue by ispedals** [yehoshuadimarsky/bcpandas#45]
Document the API for this module, preferably in the readme.

If you agree that the documentation should be added to the readme, I am willing to write it up and make a pull request.

**Comment by yehoshuadimarsky** [comment]
just saw this. sure, go ahead thanks

**Comment by vlasvlasvlas** [comment]
Let me know if i can help with this one.

**Comment by yehoshuadimarsky** [comment]
probably can just use Sphinx to autogenerate it all

**Comment by yehoshuadimarsky** [comment]
Following up - anyone want to pick this up? If not I'll close this issue in a few days

**Comment by yehoshuadimarsky** [comment]
closing this, appears abandoned. You are welcome to re-open it if you want to revisit this
