### ISSUE TITLE
Roadmap

### ISSUE THREAD

**Issue by Harshitg** [yehoshuadimarsky/bcpandas#5]
I have been following this project for a while and wanted to thank you for implementing this idea. Would you be able to sort of list down the roadmap for this project?

**Comment by yehoshuadimarsky** [comment]
Hey, thanks for suggesting this. I didn't yet write up a formal-ish roadmap but I'm sort of using the TODO.md file to track that. As there hasn't really been much traffic here on this project yet, I didn't feel like there was enough of an audience to justify writing up a roadmap, it was kind of just in my head. But I'll work on it.

Offhand I can say that I am now focusing on really getting the `to_sql` method working and fully tested, and then to work on the benchmarks. I'm sort of placing `read_sql` on the back burner for now for 2 reasons: there are some harder things to work out, and the speed benefit of using BCP vs. built-in pandas methods is much much bigger in `to_sql` then `read_sql`, but I hope to formalize that measurement when I get to the benchmarks.

If you would like to contribute to the codebase, I'd welcome that! Please open a PR and we can take it from there.

**Comment by Harshitg** [comment]
Thanks for ideation. Few questions:

1. Do you have plans to bring the delimiter to the front end, where a user can decide depending upon the data what delimiter to use?
2. While going through the benchmark for pd.to_sql, it would be worthwhile to consider `fast_executemany` 
3. Would it be possible to improve these benchmarks further by concurrently writing to mssql for e.g. a dataset with size (10 million x 6)

**Comment by yehoshuadimarsky** [comment]
>Do you have plans to bring the delimiter to the front end, where a user can decide depending upon the data what delimiter to use?

Good idea, maybe after everything else is stable. Submit a PR if you want.

>While going through the benchmark for pd.to_sql, it would be worthwhile to consider fast_executemany

Good idea, will do

>Would it be possible to improve these benchmarks further by concurrently writing to mssql for e.g. a dataset with size (10 million x 6)

I can try, but it would take a **LONG** time for the pandas method - I think several hours. You are welcome to try it and submit a PR, or maybe one day I'll do it in a VM or something.

**Comment by Harshitg** [comment]
I ran some initial benchmarks on a windows machine with mssql DB and the results are as follows:
bcpandas
`
bcpandas.to_sql(results1, 'cashflow_data',creds, if_exists='append',index = False, debug = True, batch_size=100000)`

```
1400000 rows copied.
Network packet size (bytes): 4096
Clock Time (ms.) Total     : 7984   Average : (175350.70 rows per sec.)
0:01:13.293266
```

Pandas with fastexecute_many
%%time_it
`results1.to_sql('cashflow_data',engine2, if_exists='append',index = False,chunksize=100000)
`
0:00:51:291201

I thi

**Comment by yehoshuadimarsky** [comment]
weird, not sure you ran it correctly. I just ran it myself and posted the results to the README. Closing this issue for now.

**Comment by Harshitg** [comment]
Thanks, i will post my test data and script for your to verify.

**Comment by Harshitg** [comment]
So here are the results of the most recent run using bcpandas. The test details are as follows:

The dataframe is called results1 (1,000,000 x 13) and the size is as follows:

![image](https://user-images.githubusercontent.com/1675591/74458377-9e484080-4eaf-11ea-92ca-46b212f6b5da.png)

The dtypes details is as follows:

![image](https://user-images.githubusercontent.com/1675591/74460358-c7b69b80-4eb2-11ea-91b1-6b9e08489864.png)


BCPandas version: 0.2.7
The code used is something like this:

```
from bcpandas import SqlCreds
import bcpandas as bcpandas

creds = SqlCreds('LAPTOP-BCPANDAS', 'BCPANDAS', 'BCPANDAS', 'BCPANDAS', driver_version=17)
creds.engine

x = datetime.now()
bcpandas.to_sql(results1, 'TABLE_NAME',creds, if_exists='append',index = False, debug = True, batch_size = 100000)
y = datetime.now() - x
print(y)
```

Debug output:
```
Starting copy...
100000 rows sent to SQL Server. Total sent: 100000
100000 rows sent to SQL Server. Total sent: 200000
100000 rows sent to SQL Server. Total sent: 300000
100000 rows sent to SQL Server. Total sent: 400000
100000 rows sent to SQL Server. Total sent: 500000
100000 rows sent to SQL Server. Total sent: 600000
100000 rows sent to SQL Server. Total sent: 700000
100000 rows sent to SQL Server. Total sent: 800000
100000 rows sent to SQL Server. Total sent: 900000
100000 rows sent to SQL Server. Total sent: 1000000

1000000 rows copied.
Network packet size (bytes): 4096
Clock Time (ms.) Total     : 7125   Average : (140350.88 rows per sec.)
0:02:52.376345

```

Few observations:

1. Even after specifying driver_version=17, the driver used is 13
2. Clock time shown is 7.125 seconds, however if i time the entire run it took close to 2 min 52 seconds. Could it be the time taken to break the file into individual CSV's, saving, reading and finally bcp?

Hope this is helpful, let me know if you need any additional information
