### ISSUE TITLE
latin1 issue, fixed

### ISSUE THREAD

**Issue by vlasvlasvlas** [yehoshuadimarsky/bcpandas#53]
![imagen](https://user-images.githubusercontent.com/4071796/157054112-4e6b5950-c236-4076-b302-5b974af1767e.png)

Hi! i was having some trouble writing into sqlserver with latin1, i made this fix on tmp csv creation file, 

file: main.py,
line added: 409

I thing this should be a param. If you like i can work out this one and make a pull request.

**Comment by yehoshuadimarsky** [comment]
sure go ahead
