### ISSUE TITLE
"Data contains all of the possible quote characters" what strategy can i made?

### ISSUE THREAD

**Issue by vlasvlasvlas** [yehoshuadimarsky/bcpandas#55]
hi! i got the "Data contains all of the possible quote characters", what strategy do you suggest? thanks

**Comment by yehoshuadimarsky** [comment]
change your data? Or theoretically we can change the code to try all possible ASCII values instead of just https://github.com/yehoshuadimarsky/bcpandas/blob/1d51c036e07ba25244e369c69e68f8f127056f50/bcpandas/constants.py#L38

**Comment by vlasvlasvlas** [comment]
Thanks! I'll try that :)
