### ISSUE TITLE
Help or Feature request

### ISSUE THREAD

**Issue by dorel14** [yehoshuadimarsky/bcpandas#6]
Hello 
Iused to use FreeTds as my odbc driver for my MsSQL connection , is it possible to use it with bcpandas ?
[https://gist.github.com/rduplain/1293636](url)

Thx

**Comment by yehoshuadimarsky** [comment]
Hi, per Microsoft's docs (https://docs.microsoft.com/en-us/sql/tools/bcp-utility?view=sql-server-ver15#system-requirements) it appears that the BCP utility only supports the Microsoft ODBC driver, so no, you cannot use the FreeTDS driver.
