### ISSUE TITLE
special characters in bcp auth

### ISSUE THREAD

**Issue by joelsonoda** [yehoshuadimarsky/bcpandas#65]
If I have special characters in my username/password , the pyodbc connection will work appropriately, but the bcp command will get an invalid username/password.

I believe that the special characters are being handled in the shell for bcp. For example, if my username is user$name and my password is pas$word, the resulting credentials passed to sql server would be username: user, password: pas

**Comment by digitalfuller** [comment]
I have the same issue with the $ character in the password when running in a Linux container.
I have tried to escape the $ character in the password using "\\$" in my python code when creating the SqlCreds object but that still fails to login (I have also tried to surround the password with single and double quotes but no luck there either).

If I shell into the container and run the bcp command manually (using the arguments logged by bcpandas) but using \$ in the password the bcp command works as expected.

Has anyone found a successful workaround?

**Comment by Salazander** [comment]
This PR fixes the issues we're having with `$` characters in our passwords. 
@joelsonoda @digitalfuller Would this fix also help with the issues you have reported?

**Comment by joelsonoda** [comment]
@Salazander , I looked over the changes from #88, and I believe that would solve my issue for having bash special characters in the password, however it doesn't look like it would escape the username from the credentials.

**Comment by joelsonoda** [comment]
Looks great now

**Comment by digitalfuller** [comment]
Looks good to me too, thanks 👍
