### ISSUE TITLE
Issue using Windows Auth

### ISSUE THREAD

**Issue by SimonStride** [yehoshuadimarsky/bcpandas#9]
Hi Josh,

Awesome library - thanks! Currently working great (and runs really fast!) with SQL Auth but cannot create SqlCreds with blank username & password. The intended behaviour is to default to a Windows Auth connection - but this does not quite work:

````python
from bcpandas import SqlCreds

creds = SqlCreds(server=".", database="Sandbox")
````
...fails with error: `AttributeError: 'SqlCreds' object has no attribute 'username'`.

I've written a fix and associated Unit Tests - happy to contribute a PR if that's ok with you?

Many thanks again,

Simon

**Comment by yehoshuadimarsky** [comment]
Hi Simon, thanks for the kind words. Absolutely, please do submit the PR, thanks for your proactive assistance with this. I've been meaning to implement this, but I never got around to it because 

1. I don't personally use Windows auth, so never was relevant yet
2. I couldn't find how to test this in Docker

**Comment by SimonStride** [comment]
Hi Josh, 

Apologies for the slow reply, been down a few rabbit holes with this one and life getting in the way! PR submitted at long last :-)

I've resolved the Windows Auth issue I reported, I can successfully test locally but difficult to write any automated tests for Docker images (AFAIK AD Authentication is still unsupported in Linux) so have had to settle for Unit Tests against the generated connection string and making sure the `with_krb_auth` param gets set to True.

Along the way I've had to add the Port number as a parameter of SqlCreds - defaults to 1433 so shouldn't break anything currently expecting that - but also allows you to set the Port to None for named pipes.

Hope that all makes sense and is up to standard! Happy to hear feedback/comments/changes on this.

Thanks again,

Simon

**Comment by yehoshuadimarsky** [comment]
Looks great, thanks for the PR and the tests. Don't think we will realistically be able to test the Windows auth with Docker at this point, so looks like we will have to rely on the unit tests as you created them.

#10 resolves this, so I will close it.
