### ISSUE TITLE
Re: Adding Another Maintainer

### ISSUE THREAD

**Issue by yehoshuadimarsky** [yehoshuadimarsky/bcpandas#90]
Hi all, I see that there's been an uptick in PRs and issues in the past few months, I'm grateful people are finding this library useful and are engaging and using it. But to be honest, I have kind of stopped maintaining it, because I don't have a use case for this anymore. When I created it, it was something I needed at the time, but after changing jobs and circumstances, I'm not really maintaining this anymore.

That said: I'm open to adding one or more people to this repo with admin privileges, to become a maintainer along with me. If you are interested, please reply in the comments! Thanks all.

**Comment by borchero** [comment]
@yehoshuadimarsky I would be keen on becoming a maintainer here. While I likely won't be diligently working through open PRs, we're actively using this library and I would love to be able to (regularly) contribute fixes/improvements.

**Comment by yehoshuadimarsky** [comment]
Thanks! Will add you to the repo with write permissions

**Comment by borchero** [comment]
Thanks a lot @yehoshuadimarsky! Unless you still want to have a look at (a couple of) PRs, could you maybe lift the restriction to require a reviewer’s approval to merge (until there is a second active maintainer)? Otherwise, I won’t be able to merge my own PRs 😅

**Comment by yehoshuadimarsky** [comment]
Just did

**Comment by NodeJSmith** [comment]
@yehoshuadimarsky I'm actively using this package and would be happy to be added as a maintainer.

**Comment by yehoshuadimarsky** [comment]
> @yehoshuadimarsky I'm actively using this package and would be happy to be added as a maintainer.

Thanks, appreciate the kind offer. I think we are ok now with me and @borchero, but thanks again
