### ISSUE TITLE
Package upload fails

### ISSUE THREAD

**Issue by borchero** [yehoshuadimarsky/bcpandas#99]
Hey @yehoshuadimarsky! I'm trying to publish a new version with a bunch of PRs that I merged but somehow, the PyPi upload does not work: see https://github.com/yehoshuadimarsky/bcpandas/actions/runs/3991703832/jobs/6846781668.

Could you maybe check whether your credentials are expired?

**Comment by yehoshuadimarsky** [comment]
Not sure, but I can add you as a maintainer in PyPI too if you want, let me know.

**Comment by yehoshuadimarsky** [comment]
Actually never mind, I updated the credentials to PyPI to use a token like [here](https://pypi.org/help/#apitoken), and reran the GH action, looks like that worked. Thanks for your help and all your contributions!

**Comment by borchero** [comment]
Nice, thanks a lot for your swift reply 🙌🏼
